# Generated by Django 4.0.8 on 2023-12-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_newsandevents_id_alter_semester_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='posted_as',
            field=models.CharField(choices=[('News', 'خبر'), ('Event', 'حدث')], max_length=10, verbose_name='نوع المنشور'),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='العنوان'),
        ),
    ]
