# Generated by Django 4.0.8 on 2023-12-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachloar', 'دبلوم عالي'), ('Master', 'ماجستير')], max_length=25, null=True),
        ),
    ]
