# Generated by Django 4.0.8 on 2023-12-15 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TakenCourse',
        ),
    ]
